version: '3.8'
services:

    # Application & web server
    app:
        build:
            context: .
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - "mysql-app"
        ports:
            - 8080:80
    # Database
    mysql-app:
        image: mysql:8.0
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            MYSQL_USER: root
        ports:
            - "33061:3306"

volumes:
    dbdata:
